### ISSUE TITLE
Documentation has my_project.update(), though the update() method has been removed

### ISSUE THREAD

**Issue by pchr8** [konfuzio-ai/konfuzio-sdk#126]
Quick FYI: Both the current GitHub README and https://dev.konfuzio.com/sdk/examples/examples.html use the `update()` method, but both master and 0.2.4 don't have it as separate method anymore.

**Comment by pchr8** [comment]
Same goes for get_documents_by_status() - two is a pattern - probably the documentation is of an older version and all this is known to you, disregard in this case :)

**Comment by genego-io** [comment]
@pchr8: Nice catch! Seems like `update()` was superseded by `my_project.get(update=True)` [here](https://github.com/konfuzio-ai/konfuzio-sdk/blob/master/konfuzio_sdk/data.py#L2467). `get_documents_by_status()` apparently was phased out, but the functionality still could use a relevant code example. I created a new internal ticket to solve this (#9906 for reference). Documentation should be updated shortly.

**Comment by da-konfuzio** [comment]
Hi @pchr8, thank you for flagging this.

I have updated the documentation at https://dev.konfuzio.com/sdk/examples/examples.html

The GitHub README will undergo some changes (internal ticket #10183), so I recommend using dev.konfuzio.com for the moment. I will keep you posted.

**Comment by da-konfuzio** [comment]
Hi @pchr8, the GitHub README and the documentation at dev.konfuzio.com will be updated in the coming days (it will be available when we merge https://github.com/konfuzio-ai/konfuzio-sdk/pull/185).

**Comment by da-konfuzio** [comment]
README and documentation at dev.konfuzio.com have been updated.
